### ISSUE TITLE
Gandi doesn't appear in the DDNS dropdown list

### ISSUE THREAD

**Issue by Guts** [kofemann/livedns4synology#2]
Hi,

I'm trying to set up the DDNS with Gandi with your script but I'm facing some issues:

- Python is already available in its version 3 on my Synology (DS215+ with DSM 7) and can't be installed neither activated through the package manager
- the `USER_Gandi LiveDNS` doesn't appear in the DDNS provider list, even after addind the relevant section in the providers conf as described into the README

**Comment by kofemann** [comment]
Can you post the section here? Do you see any errors in the logs?

this is what I have:
```
[USER_Gandi LiveDNS]
	modulepath=/usr/local/bin/livedns.py
	queryurl=Gandi
```
system info:
```
$ python --version
Python 3.8.8
```
```
$ cat /etc/VERSION 
majorversion="7"
minorversion="0"
major="7"
minor="0"
micro="1"
productversion="7.0.1"
buildphase="GM"
buildnumber="42218"
smallfixnumber="2"
nano="2"
base="42218"
builddate="2022/01/12"
buildtime="15:16:03"
$ 
```

**Comment by Guts** [comment]
Python version:

```bash
$ python --version
Python 3.8.8
```

Sys info:

```bash
$ cat /etc/VERSION 
majorversion="7"
minorversion="0"
major="7"
minor="0"
micro="1"
productversion="7.0.1"
buildphase="GM"
buildnumber="42218"
smallfixnumber="2"
nano="2"
base="42218"
builddate="2022/01/12"
buildtime="15:16:03"
```

Providers:

```bash
$ tail /etc.defaults/ddns_provider.conf 
        modulepath=DynDNS
        queryurl=ddns.oray.com/ph/update?hostname=__HOSTNAME__&myip=__MYIP__
[Synology]
        modulepath=Synology
        queryurl=ddns.synology.com
        register_module=synology
        website=https://account.synology.com
[USER_Gandi LiveDNS]
        modulepath=/usr/local/bin/livedns.py
        queryurl=Gandi
```

Installed script:

```bash
$ python /usr/local/bin/livedns.py 
Usage: livedns <username> <api key> <fqdn> <ip>
```


DDNS dropdown list (in French):

![image](https://user-images.githubusercontent.com/1596222/154144694-6ac3e697-a6b3-4248-8e90-41be06d170f3.png)

**Comment by Guts** [comment]
@kofemann I think I've found out: the conf filepath is not correct. If I edit this one `/etc/ddns_provider.conf `, it appears... Can you confirm please?

And can you provide a screen shot of your own dropdown list please? to compare

**Comment by kofemann** [comment]
Yrs, on my system as well the changes are made in `/etc/ddns_provider.conf`

**Comment by Guts** [comment]
Does that mean that both files must be edited?
If so, could you add this path to your README please? I can fork & PR but it's quite a big workflow for so little modifications...

**Comment by kofemann** [comment]
No, only in `/etc/ddns_provider.conf` probably the older version have required in `defaults`. I don't remember anymore :man_shrugging: . I will update the README.
